/**
 * Technology tree, researched with knowledge points (📖) generated by
 * teachers at the school. First batch covers the settled-era openers;
 * bronze/iron eras extend this list in later phases.
 */

export interface Tech {
  id: string;
  label: string;
  icon: string;
  cost: number;
  requires?: string;
  desc: string;
}

export const TECHS: Tech[] = [
  {
    id: 'agriculture',
    label: 'Agriculture',
    icon: '🌾',
    cost: 15,
    desc: 'Unlocks the crop field. Sow in spring, tend in summer, harvest in autumn.',
  },
  {
    id: 'cropRotation',
    label: 'Crop rotation',
    icon: '🔄',
    cost: 25,
    requires: 'agriculture',
    desc: 'Harvests yield +50% food.',
  },
  {
    id: 'herbLore',
    label: 'Herb lore',
    icon: '🌿',
    cost: 15,
    desc: 'Herbalists gather +50% herbs per trip. Herbs (with an assigned herbalist) halve an illness.',
  },
  {
    id: 'medicine',
    label: 'Medicine',
    icon: '💊',
    cost: 10,
    requires: 'herbLore',
    desc: 'The herbalist brews 1 medicine from 2 herbs. Medicine halves an illness and prevents death by sickness.',
  },
  {
    id: 'clayWorking',
    label: 'Clay working',
    icon: '🏺',
    cost: 20,
    desc: 'Unlocks the clay pit — dig clay from deposits near water.',
  },
  {
    id: 'weaving',
    label: 'Looming & weaving',
    icon: '🧶',
    cost: 10,
    desc: "Unlocks the weaver's cottage — straw becomes string, string becomes linen.",
  },
  {
    id: 'leatherworking',
    label: 'Leatherworking',
    icon: '💼',
    cost: 10,
    desc: 'Unlocks the tannery (at the waterline): hides become leather for fine clothing and boots.',
  },
  {
    id: 'cobbling',
    label: 'Cobbling',
    icon: '👞',
    cost: 10,
    desc: "Unlocks the cobbler's shop. The unshod walk 10% slower and lose 5 happiness.",
  },
  {
    id: 'pottery',
    label: 'Pottery',
    icon: '🏺',
    cost: 20,
    requires: 'clayWorking',
    desc: "Unlocks the potter's workshop — households furnished with pots are happier.",
  },
  {
    id: 'brickMaking',
    label: 'Brick making',
    icon: '🧱',
    cost: 30,
    requires: 'clayWorking',
    desc: 'Unlocks the brick oven (clay + firewood → bricks) and the brick house: 6 beds, stays warm far longer.',
  },
  {
    id: 'baking',
    label: 'Baking',
    icon: '🍞',
    cost: 25,
    requires: 'agriculture',
    desc: 'Unlocks the bakery oven — flour and firewood become bread, the finest table food.',
  },
  {
    id: 'trade',
    label: 'Trade',
    icon: '🤝',
    cost: 30,
    desc: 'Unlocks the trading post — passing caravans buy and sell goods there.',
  },
  {
    id: 'education',
    label: 'Education',
    icon: '🏫',
    cost: 30,
    desc: 'Unlocks the school — teachers double knowledge output, and children learn.',
  },
  {
    id: 'feudalism',
    label: 'Feudalism',
    icon: '👑',
    cost: 40,
    desc: 'Unlocks stone walls, stone gates, and the Manor. Once the Manor stands, a citizen is raised to baron.',
  },
  {
    id: 'religion',
    label: 'Religion',
    icon: '⛪',
    cost: 30,
    desc: 'Unlocks the Temple: +10 happiness for up to 100 villagers.',
  },
  {
    id: 'warcraft',
    label: 'Warcraft',
    icon: '🛡️',
    cost: 20,
    desc: 'Unlocks the training ground, weaponsmith, and watchtower — the means to defend your people or take what is theirs.',
  },
  {
    id: 'mining',
    label: 'Mining',
    icon: '⛏️',
    cost: 25,
    desc: 'Unlocks the mine — dig copper, tin, iron, and coal from mountain ore deposits.',
  },
  {
    id: 'bronzeWorking',
    label: 'Bronze working',
    icon: '🥉',
    cost: 35,
    requires: 'mining',
    desc: 'Unlocks the smelter (copper + tin → bronze bars) and bronze tools — 35% faster than bare hands.',
  },
  {
    id: 'ironWorking',
    label: 'Iron working',
    icon: '⚔️',
    cost: 50,
    requires: 'bronzeWorking',
    desc: 'Smelt iron bars (iron ore + coal) and craft iron tools — the finest working edge known.',
  },
];

export function techById(id: string): Tech {
  return TECHS.find((t) => t.id === id)!;
}
